hitfix: crash when error_message is set
Attribute data is read only,  must be set by setter.

```
...
  File "/usr/local/lib/python3.6/site-packages/behave_html_pretty_formatter/html_pretty.py", line 480, in generate_scenario
    self.report_error(self._scenario)
  File "/usr/local/lib/python3.6/site-packages/behave_html_pretty_formatter/html_pretty.py", line 445, in report_error
    self.reported_error.data = behave_obj.error_message
AttributeError: can't set attribute
```